# common env config for most services
x-base-env: &base-env
  TZ: ${TZ}
  PUID: ${PUID}
  PGID: ${PGID}


x-vpn-service: &vpn-service
  network_mode: service:vpn  # implies depends_on for vpn
  restart: always
  healthcheck:
    # appears that services behind the vpn lose access to the network after it reconnects
    # if we can't ping the vpn, then it probably restarted/reconnected
    # exit the container and let it restart.
    test: ping -c 2 vpn || kill 1
    interval: 30s
    timeout: 2s
    retries: 1
    start_period: 10s  # wait a little for the vpn to reconnect first


# common config for the non-vpn'd *arr servicers
x-arr-service: &arr-service
  environment:
    <<: *base-env
  restart: unless-stopped



networks:
  arr-net:
    ipam:
      config:
       - subnet: 10.10.10.0/24



volumes:
  dispatcharr_data:



services:
  jellyfin:
    image: ghcr.io/jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      <<: *base-env
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - ./config/jellyfin:/config
      - ./cache:/cache
      - type: bind
        source: /data/media/movies
        target: /films
      - type: bind
        source: /data/media/tv
        target: /series
    networks:
      - arr-net



    # sonarr
  Sonarr:
      image: lscr.io/linuxserver/sonarr:latest
      container_name: sonarr
      hostname: sonarr
      <<: *arr-service
      logging:
        driver: json-file
      ports: 
        - 8989:8989
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - ./config/sonarr:/config
        - /data:/data
      networks:
        arr-net:
          ipv4_address: 10.10.10.2


  Radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    <<: *arr-service
    logging:
      driver: json-file
    ports: 
      - 7878:7878 ## ui port
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/radarr:/config
      - /data:/data
    networks:
      arr-net:
        ipv4_address: 10.10.10.3

  
  # Dispatcharr
  dispatcharr:
    image: ghcr.io/dispatcharr/dispatcharr:latest
    hostname: dispatcharr
    restart: unless-stopped
    container_name: dispatcharr
    <<: *arr-service
    ports:
      - 9191:9191
    volumes:
      - dispatcharr_data:/data
    environment:
      - DISPATCHARR_ENV=aio
      - REDIS_HOST=localhost
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - DISPATCHARR_LOG_LEVEL=info



  # seerr
  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: seerr
    hostname: seerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
      - PORT=5055
    ports:
      - 5055:5055
    volumes:
      - ./config/seerr:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/settings/public || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped

  Prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    <<: *vpn-service
    logging:
      driver: json-file
    environment:
        <<: *base-env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/prowlarr:/config
      - /data:/data

  
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    <<: *vpn-service
    environment:
      <<: *base-env
      UMASK_SET: 022
      WEBUI_PORT: 8090
    volumes:
        - ./config/qbittorrent:/config
        - /data:/data




  vpn:
    image: qmcgaw/gluetun
    container_name: vpn
    hostname: vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1
    environment:
      TZ: ${TZ}
      VPN_SERVICE_PROVIDER: protonvpn
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}
      VPN_PORT_FORWARDING: 'on'
      VPN_PORT_FORWARDING_PROVIDER: protonvpn
      HEALTH_SUCCESS_WAIT_DURATION: 30s
      DNS_ADDRESS: 8.8.8.8
    volumes:
      - ./config/wireguard/config:/config
    ports:
      # expose ports for services behind vpn
      - 8090:8090 # qbittorrent ui
      - 9696:9696 # prowlarr ui
    networks:
      arr-net:
        ipv4_address: 10.10.10.10
    extra_hosts:
      # use static ips for non-vpn'd services, map hostnames here (e.g. for prowlarr)
      - sonarr=10.10.10.2
      - radarr=10.10.10.3
    restart: always